:: --------------------------------------------------------
:: This file was generated by NI VeriStand Model Framework
:: Version : 2019.0.0.0 (2019)
:: Generated on : 07-Jul-2020 13:42:37
:: --------------------------------------------------------

set MATLAB=D:\MATLAB\R2018a
set VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\
call "D:\VeriStand\2019\ModelInterface\tmw\toolchain\nivs_vcvars32_100.bat"
@if errorlevel 1 goto error_exit


:make
cd /d %~dp0
nmake -f plant1_start_4_1.mk  EXT_MODE=0 EXTMODE_STATIC_ALLOC=0 TMW_EXTMODE_TESTING=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 MAT_FILE=1 NIDEBUG=0 NIOPT="Default" OPTS="" COMBINE_OUTPUT_UPDATE_FCNS=0 INCLUDE_MDL_TERMINATE_FCN=1 MULTI_INSTANCE_CODE=0 ISPROTECTINGMODEL=NOTPROTECTING /I

 
@if errorlevel 1 goto error_exit
exit /B 0

:error_exit
echo The make command returned an error of %errorlevel%
An_error_occurred_during_the_call_to_make
